---

- hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Change host name
      ios_config:
        lines:
          - hostname ROUTER1
    - name: show hostname
      ios_command:
        commands: sh run | s hostname
      register: output
    - name: print output
      debug:
        var: output.stdout
