---
- hosts: all
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Run CLI for hostname change
      block:
      - name: Run cli_command on Cisco IOS
        ansible.netcommon.cli_command:
          command: hostname Router2-Ansible
        register: output

      - name: Display result to terminal window
        debug:
          var: result.stdout_lines
      when: ansible_network_os == 'cisco.ios.ios'
