---
- hosts: CiscoR2
  gather_facts: false

  tasks:

    - name: Change hostname
      ios_config:
        lines:
          - hostname Ansible_ROUTER2
    - name: show hostname
      ios_command:
        commands: sh run | s hostname
      register: output
    - name: print output
      debug:
        var: output.stdout
