---
- hosts: all
  gather_facts: false
  connection: ansible.netcommon.network_cli
  
  tasks:
    - name: Configure top level configuration
      cisco.ios.ios_config:
        lines: hostname Ansible-Router02

    - name: Configure interface settings
      cisco.ios.ios_config:
        lines:
          - description test ansible interface
          - ip address 172.31.1.1 255.255.255.0
          - no sh
        parents: interface Ethernet0/1
