---

- hosts: all
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:

  - name: show ip int br
    ansible.netcommon.cli_command:
      commands: sh ip int br
    register: output

  - name: print output
    debug:
      var: output.stdout_lines
