---

- hosts: all
  gather_facts: false
  connection: local

  tasks:

  - name: show ip int br
    ios_command:
      commands: sh ip int br
    register: output

  - name: print output
    debug:
      var: output.stdout_lines
